# Generated by Django 5.2.5 on 2025-08-21 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_receita_delete_receitas'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='imgage',
            new_name='image',
        ),
    ]
